Timestamp and URL available in the response object
VikeLabs/scheduler-scraper pull request #103
Opened 2021-02-27 00:44 UTC by shergillmanav19

My index.test.ts file is throwing weird errors so i wasnt able to test but hopefully its good. 
<img width="1028" alt="Screen Shot 2021-02-26 at 4 35 55 PM" src="https://user-images.githubusercontent.com/55296628/109369578-b3d99f80-7851-11eb-8e8b-3509646b9f13.png">

2021-02-27 01:25 UTC, isaaccormack commented
Try adding `"resolveJsonModule": true,` to your tsconfig.json to fix the error you posted here.

2021-02-27 01:28 UTC, shergillmanav19 commented
> Try adding `"resolveJsonModule": true,` to your tsconfig.json to fix the error you posted here.

Already have that haha i think its a VS glitch since the file can run?

2021-02-27 02:13 UTC, isaaccormack commented
Hmmm, I'm on intellij so I haven't run into anything like that. Regardless, you'll need to be able to run the tests before we can review this PR.

Try messing around with your VSCode settings and googling this issue a bit to see if you can find a resolution. I can try to help out if you need.

2021-02-27 04:06 UTC, shergillmanav19 commented
> Hmmm, I'm on intellij so I haven't run into anything like that. Regardless, you'll need to be able to run the tests before we can review this PR.
> 
> Try messing around with your VSCode settings and googling this issue a bit to see if you can find a resolution. I can try to help out if you need.

Tests are all passing now i believe!

2021-02-27 04:36 UTC, isaaccormack requested changes

2021-02-27 04:36 UTC, isaaccormack commented on src/__tests__/index.test.ts
> +    const parsedData = await UVicCourseScraper.getAllCourses();
would be cleaner if this was just `const { data } = await client.getCourseDetails('SENG', '360');` and then use data instead of allCourses. its clear what data is from context

2021-02-27 04:36 UTC, isaaccormack commented on src/index.ts
> +    const tmp_Date = new Date();
just call this `date` instead of `tmp_Date`

also a side note - your mixing camelCasing with underlining here, so it would either be tmpDate or tmp_date. the former is used in this project, the later is common in languages like C and Python

2021-02-27 04:36 UTC, isaaccormack commented on src/index.ts
> +    return { data: courseCatalog, timestamp: timestamp, URL: URL };
this should all just be inlined

2021-02-27 04:36 UTC, isaaccormack commented on src/index.ts
> +  public static async getAllCourses(): Promise<{ data: KualiCourseCatalog[]; timestamp: string; URL: string }> {
should make a new object here called KualiCourseCatalogResponse which consists of this, would be much more readable

2021-02-28 01:40 UTC, aomi commented on src/index.ts
> +  public static async getAllCourses(): Promise<{ data: KualiCourseCatalog[]; timestamp: string; URL: string }> {
I think it should be added to the `KualiCourseCatalog` interface tbh. The time and URL are for audit reasons related to the data we provide so I feel it's essential that can be part of the main interface.

2021-02-28 01:40 UTC, aomi commented on src/index.ts
> +    const tmp_Date = new Date();
eslint rules inbound

2021-03-01 03:41 UTC, shergillmanav19 commented on src/index.ts
> +  public static async getAllCourses(): Promise<{ data: KualiCourseCatalog[]; timestamp: string; URL: string }> {
If I add both of them to KualiCourseCatalog then the array returned will have the same date and URL which is unnecessary but I'm willing to do it either way. Let me know

2021-03-01 04:14 UTC, isaaccormack commented on src/index.ts
> +  public static async getAllCourses(): Promise<{ data: KualiCourseCatalog[]; timestamp: string; URL: string }> {
good point, it does seem like returning a `KualiCourseCatalogRes` would be more natural in that case but I could go either way...

2021-03-01 04:18 UTC, isaaccormack requested changes

2021-03-01 04:18 UTC, isaaccormack commented on src/__tests__/index.test.ts
> +    const allCourses = (await UVicCourseScraper.getAllCourses()).data;
is there a reason we cant use destructuring everywhere? ie. `const { data } = await UVicCourse...`

2021-03-01 07:15 UTC, shergillmanav19 commented on src/__tests__/index.test.ts
> +    const allCourses = (await UVicCourseScraper.getAllCourses()).data;
i missed the first comment where you said to do that haha my bad will do that 😅

2021-03-06 19:17 UTC, isaaccormack commented on src/index.ts
>      const courseDetails = await UVicCourseScraper.getCourseDetailsByPid(pid);
why is this not using destructuring?

2021-03-06 19:19 UTC, aomi commented on src/index.ts
>      const courseDetails = await UVicCourseScraper.getCourseDetailsByPid(pid);
Why are we casting here?

2021-03-06 19:22 UTC, shergillmanav19 commented on src/index.ts
>      const courseDetails = await UVicCourseScraper.getCourseDetailsByPid(pid);
not sure I think that's Issac's code @aomi

2021-03-06 19:27 UTC, aomi commented on src/index.ts
> +    return { data: await detailedClassInfoExtractor($), timestamp: new Date().toISOString(), URL: URL };
I'd prefer lowercase for `url`. another note is if the attribute you're adding to a object is the same you can just do `url` without doing `url: url`

2021-03-06 20:25 UTC, shergillmanav19 commented on src/index.ts
>      const courseDetails = await UVicCourseScraper.getCourseDetailsByPid(pid);
i tried removing the casting but then it throws an error of `string | undefined cannot be assigned to type string` I'm assuming this happens because we're getting the PID from a map? and it could be undefined if it doesn't exist in there so we have to cast it as a string

2021-03-06 20:25 UTC, shergillmanav19 commented on src/index.ts
> +    return { data: await detailedClassInfoExtractor($), timestamp: new Date().toISOString(), URL: URL };
yep, thats done!

2021-03-07 03:09 UTC, isaaccormack commented on src/index.ts
>      const courseDetails = await UVicCourseScraper.getCourseDetailsByPid(pid);
^this, and yes that is my code

2021-03-07 03:10 UTC, isaaccormack approved these changes
LGTM

2021-03-21 05:38 UTC, merged