Updated README and created a helper file to help in getting started
VikeLabs/scheduler-scraper pull request #33
Opened 2020-10-31 20:29 UTC by keithradford

Added a getting started list to README to help people contributing to this project.
Also create example.js which can hopefully help people understand cheerio and RegEx in the context of how we're using it to parse data for this project.

2020-10-31 20:58 UTC, aomi requested changes

2020-10-31 20:58 UTC, aomi commented on example.js
> +const request = require('request');
That package isn't available I think. Use `got` which is already in the repo.

2020-10-31 20:58 UTC, aomi commented on example.js
> +const request = require('request');
Why is this in `js`?

2020-11-01 00:34 UTC, keithradford commented on example.js
> +const request = require('request');
Got it, will change

2020-11-01 00:34 UTC, keithradford commented on example.js
> +const request = require('request');
So people can easily run it with node, thoughts?

2020-11-01 00:52 UTC, aomi commented on example.js
> +const request = require('request');
You can use `npx ts-node-dev example.ts` for example to run that file that is TypeScript 💯

2020-11-01 01:30 UTC, aomi approved these changes

2020-11-01 01:30 UTC, aomi commented on .gitignore
> +example.js
I don't think we need this here.

2020-11-01 01:34 UTC, keithradford commented on .gitignore
> +example.js
Oh yeah I can change that to ts (or remove) but I put it there so it could stay consistent in the repo but people could mess around with it without commiting changes

2020-11-01 01:36 UTC, merged