Detailed course information -- requirements data
VikeLabs/scheduler-scraper pull request #37
Opened 2020-11-03 07:25 UTC by J-Raymer

I changed the index.test file and the data structure for the requirements data. I also hard coded the return value for what I was planning for this. Is this structure ok? I still need to figure out how to scrape the data properly return it in this format.

2020-11-03 07:35 UTC, aomi commented on src/pages/detailedClassInformation/__tests__/index.test.ts
> +    expect(parsed.requirements.fieldOfStudy).toStrictEqual(['EN: Biomedical Engineering', 'EN: Computer Engineering', 'EN: Electrical Engr', 'EN: Software Engineering BSENG']);
We might want to keep the note of the following.
> Must be enrolled in one of the following Fields of Study (Major, Minor, or Concentration):

Maybe an additional details property? 

Also for the `fieldsOfStudy` (I think plural is better for this), I think we can parse it out to just something like `['CENG', 'ELEC', ' BSENG']` etc. etc.

2020-11-03 07:35 UTC, aomi commented on src/pages/detailedClassInformation/index.ts
> +  requirements: requirements;
```
requirements: {
  level: LevelType[];
  fieldOfStudy: FieldType[];
}
```
You can grab `LevelType` from the `types.ts` file like at the top of the file and maybe make a `FieldType` property?  ie `type FieldType = 'ELEC' | 'SENG'`

2020-11-03 08:24 UTC, J-Raymer commented on src/pages/detailedClassInformation/index.ts
> +  requirements: requirements;
@aomi thanks, I have made the changes you suggested. I think the way you suggested for the field type is a better solution i.e.,  'ECE' as apposed to 'EN: Computer Engineering'. This code still needs a implementation to scrape the data properly

2020-11-16 02:10 UTC, aomi requested changes

2020-11-16 02:10 UTC, aomi commented on src/pages/detailedClassInformation/index.ts
> +  const idxEnd = requirementsInfo.findIndex(e => e === 'This course contains prerequisites please see the UVic Calendar for more information');
I think we can accomplish a lot of this with a single regex statement. @keithradford thoughts?

2020-11-16 02:10 UTC, aomi commented on src/pages/detailedClassInformation/index.ts
> +  }
This implies that the level attribute is always a single value but the interface is a list. I don't understand also why you can't assign the value directly. Also we shouldn't globally scope variable names.

2020-11-16 02:10 UTC, aomi commented on src/types.ts
> +export type levelType = 'law' | 'undergraduate' | 'graduate' | 'unknown';
A think an `undefined` is better than `'unknown'`

2020-11-16 02:10 UTC, aomi commented on src/types.ts
> +  'SOCI' | 'SENG' | 'SPAN' | 'STAT' | 'TS' | 'THEA' | 'VIRS' | 'ART' | 'WRIT';
I'm not sure what to call this type but I think it would be considered subjects? I think a field of study isn't exactly this but maybe looking at the UVic calendar might yield cleaner terminology.

2020-11-16 16:33 UTC, keithradford commented on src/pages/detailedClassInformation/index.ts
> +  const idxEnd = requirementsInfo.findIndex(e => e === 'This course contains prerequisites please see the UVic Calendar for more information');
This is true. If you look at `index.ts` I was working on for the course schedule scraper, I moved away from the array splitting strategy and just introduced a bunch of RegEx statements on the big block of text. For the pages I was working on this strategy passed tests we had for every course VS. the ~75% it was passing before when using the array.

2020-11-16 16:39 UTC, keithradford commented
I would take a look at `courseListingEntries/index.ts` to see how to do this with more RegEx. You're not far off and it shouldn't be hard to change this to use RegEx cause it will still use the same logic, it just will be more flexible in the long run. Also some of the test cases from that file might be worth copying over and modified for this file 👍

2020-11-21 22:11 UTC, J-Raymer commented
@aomi could you please take a look at my most recent commit? I decided to keep handing the data in the index.ts file as an array. I think this way it will be easy to convert the field of study data into a cleaner representation using Regex later if we decide to do so. Although after talking with @keithradford it does make sense to scrape the data as is and whoever uses the api can decide to represent it as they want.

2020-11-21 22:15 UTC, aomi commented on src/types.ts
> -export type levelType = 'law' | 'undergraduate' | 'graduate';
This shouldn't have an 'undefined' type. Instead when this type is being used you can do something like `level?: levelType;` where the `?` takes it an optional (can be undefined).

2021-01-04 00:53 UTC, aomi commented on src/types.ts
> +export type classification = 'year 1' | 'year 2' | 'year 3' | 'year 4' | 'year 5';
Does the format need to be like this? It seems kinda clunky

2021-01-04 00:53 UTC, aomi commented on src/pages/detailedClassInformation/__tests__/index.test.ts
> +    expect(classification).toStrictEqual(['Year 4', 'Year 5'])
How does this not fail the test...? (the year thing is defined to be lower-case)

2021-01-16 21:03 UTC, shergillmanav19 approved these changes

2021-01-16 22:18 UTC, aomi approved these changes

2021-01-17 03:32 UTC, merged