Parse pre co req
VikeLabs/scheduler-scraper pull request #45
Opened 2020-11-12 22:46 UTC by shergillmanav19

2020-11-12 22:54 UTC, keithradford commented
Since you created a new function, it's probably a good idea to create a test suite 👍

2020-11-12 23:02 UTC, shergillmanav19 commented
> Since you created a new function, it's probably a good idea to create a test suite 👍

👍🏽

2020-11-12 23:34 UTC, aomi requested changes

2020-11-12 23:34 UTC, aomi commented on package.json
> +    "es6": "0.0.7",
Why is this here?

2020-11-12 23:34 UTC, aomi commented on package.json
> +    "es6": "0.0.7",
We use TypeScript this shouldn't be needed.

2020-11-12 23:34 UTC, aomi commented on src/preAndCoRequisite.test.ts
> +  ];
Is there a reason to keep anything other than the subject/code? I don't think we need to grab that info  from here

2020-11-12 23:34 UTC, aomi commented on src/preAndCoRequisite.ts
> +};
This needs to be defined as a `type` or `interface`.

2020-11-13 03:46 UTC, shergillmanav19 commented on src/preAndCoRequisite.test.ts
> +  ];
im not sure what you mean?

2020-11-13 03:47 UTC, shergillmanav19 commented on src/preAndCoRequisite.ts
> +};
could i define this in types.ts?

2020-11-13 03:48 UTC, aomi commented on src/preAndCoRequisite.ts
> +};
Yup

2020-11-13 03:49 UTC, aomi commented on src/preAndCoRequisite.test.ts
> +  ];
```
 const expectedCourses = [
    'AHVS321',
    'AHVS323',
    'AHVS326',
    'AHVS328',
    'HA321',
    'HA323',
    'HA326',
    'HA328',
    'HIST236',
    'HSTR236A',
  ];
```

2020-11-13 03:53 UTC, shergillmanav19 commented on src/preAndCoRequisite.test.ts
> +  ];
Oh i see what you mean, and its because when i scrape the HTML i use the .text() so it returns me everything including the subject's description that is why i did that

2020-11-13 04:37 UTC, aomi commented on src/preAndCoRequisite.test.ts
> +  ];
I see I see. Just from the wording it makes it seem like what you defined is what you want but I would throw out the rest of the data and make the expected list simpler.

2020-11-18 05:36 UTC, keithradford approved these changes

2020-11-18 05:37 UTC, keithradford commented
Just make sure you resolve everything before you merge (it's blocked now because of that)

2020-11-18 05:43 UTC, aomi commented
@shergillmanav19 You should try and build off the recursion-based parsing to see if you can get it working a bit more.

2021-02-27 04:51 UTC, isaaccormack commented
abandoned

2021-02-27 04:51 UTC, closed without merging