Refactor/dev tools
VikeLabs/scheduler-scraper pull request #60
Opened 2020-12-09 17:46 UTC by isaaccormack

- refactor / clean up code in dev tools module
- create a clear division between dev tools and application code
- create common folder to share simple util-like code between dev-tools and within the app itself
- move example.ts into its own example folder in /src/example and its respective test cases there
- update tsconfig, npmignore, and package.json
- tested to ensure all tests are still being detected and all passing
- tested to ensure the output for all cli tools is identical to what it was before refactoring

this resolves #59

2020-12-10 03:23 UTC, aomi requested changes

2020-12-10 03:23 UTC, aomi commented on src/common/__tests__/pathBuilders.test.ts
> +describe.only('getScheduleBySubject', () => {
I don't think this was you but we should comment this out?

2020-12-10 03:23 UTC, aomi commented on src/common/__tests__/pathBuilders.test.ts
> +describe.only('getScheduleBySubject', () => {
I mean remove `.only`

2020-12-10 03:23 UTC, aomi commented on src/dev-tools/helpers.ts
> +};
This can definitely be merged into one using some TypeScript generics

2020-12-10 03:23 UTC, aomi commented on src/example-scraper/__tests__/example.test.ts
> +  each(paths).it.concurrent('%s has the expected title ', async (path: string) => {
The first `name: string` is needed to create a human-friendly output from Jest for this parameterized test. I don't think we need to type this directly either.

2020-12-10 03:23 UTC, aomi commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +  each(paths).it('%s has the expected title ', async (path: string) => {
Same thing here in regards to `name: string`

2020-12-10 04:49 UTC, isaaccormack commented on src/dev-tools/helpers.ts
> +};
I wasn't sure how to print the message in bar.interrupt generically, since once is a string and the other is a field of an object. Any ideas? Or just omit printing it?

2020-12-10 04:55 UTC, isaaccormack commented on src/example-scraper/__tests__/example.test.ts
> +  each(paths).it.concurrent('%s has the expected title ', async (path: string) => {
how so? I don't see where `name` is used?

2020-12-10 06:30 UTC, aomi commented on src/example-scraper/__tests__/example.test.ts
> +  each(paths).it.concurrent('%s has the expected title ', async (path: string) => {
It's used for the string after `concurrent`... (where `%s` is where the `name` is put in)

2020-12-10 06:31 UTC, aomi commented on src/dev-tools/helpers.ts
> +};
Is there a means of getting the name of the generic type? It's not a big deal if this is more generic at the cost of some verbose messaging imo.

2020-12-10 20:22 UTC, aomi commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +    expect(e.crn).toMatch(/\d{5}/);
Can we define this above?

2020-12-10 20:23 UTC, aomi commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +  each(namePathPairs).it('%s parses correctly', async (name: string, path: string) => {
`202101 term › WRIT 412 parses correctly` becomes the output :)

2020-12-10 20:46 UTC, isaaccormack commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +  each(namePathPairs).it('%s parses correctly', async (name: string, path: string) => {
much better than the path to the file hahaha

2020-12-10 20:48 UTC, isaaccormack commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +    expect(e.crn).toMatch(/\d{5}/);
what do you mean exactly?

2020-12-11 01:25 UTC, aomi approved these changes

2020-12-11 01:25 UTC, aomi commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +    expect(e.crn).toMatch(/\d{5}/);
move `assertFields` above where it is actually invoked.

2020-12-11 01:57 UTC, isaaccormack commented on src/pages/courseListingEntries/__tests__/index.test.ts
> +    expect(e.crn).toMatch(/\d{5}/);
for sure

2020-12-11 02:00 UTC, merged