Add usage to readme
VikeLabs/scheduler-scraper pull request #67
Opened 2020-12-27 21:44 UTC by keithradford

Added what we talked about in the meeting. Feel free to add suggestions and comment on the direction I'm taking with this. Below is an image of what it looks like in the readme so it's easier to visualize.

![image](https://user-images.githubusercontent.com/53020925/103180308-794f8880-4849-11eb-86e4-cc0037537077.png)

2020-12-28 17:13 UTC, isaaccormack commented
just added the methods we should expose to the consumer discussed in last weeks meeting to the table

also thought that API was a more fitting title than functionality

2020-12-28 17:14 UTC, isaaccormack approved these changes

2020-12-28 21:08 UTC, aomi requested changes

2020-12-28 21:08 UTC, aomi commented on README.md
> +|``getCourseDetails(subject: string, code: number)``|Returns a ``KualiCourseItem`` object with details for the course|
I don't think this can be a number because we might have courses that start with a 0? or classes that have a letter suffix at the end like `CSC349A`?

2020-12-28 22:41 UTC, keithradford commented
@isaaccormack Do you think it's worth it to add a list of attributes for each object?

2020-12-28 22:54 UTC, isaaccormack commented on README.md
> +|``getCourseDetails(subject: string, code: number)``|Returns a ``KualiCourseItem`` object with details for the course|
nice catch, thanks

2020-12-28 22:56 UTC, isaaccormack commented
@keithradford I don't think so, that means we would have to update the list of attributes on both the readme, and in the source code whenever we make changes. I think it's easy enough for the client to look at the type definitions.

2020-12-28 23:08 UTC, keithradford commented on README.md
> +|``getCourseDetails(subject: string, code: number)``|Returns a ``KualiCourseItem`` object with details for the course|
have the parts of the code that have crn in it been changed to number as well?

2020-12-28 23:14 UTC, isaaccormack commented on README.md
> +|``getCourseDetails(subject: string, code: number)``|Returns a ``KualiCourseItem`` object with details for the course|
that would be in the api which aomi is working on, the type definition for crn doesnt need to match this since it refers to crn in a different context

2020-12-28 23:45 UTC, aomi commented
I feel we should wait making this more full fledged until we finish the API. We should write the documentation, which would serve as the specification for the API or the other way around (write the API then the docs).

If we did `getCourseSections(subject: string, code: string)`, wouldn't it imply **all** sections for a given course (means every single term)

2020-12-29 17:02 UTC, isaaccormack commented
@aomi Agreed, but I think we should write the API docs first, and agree upon what endpoints we want, then write the API. Do you think we need to create an issue for that and have further discussion to extrapolate on what I have here?

Good point, maybe it should be `getCourseSectionsByTerm(term: number, subject: string, code: string)`?

2020-12-29 23:01 UTC, aomi commented
@isaaccormack I think the way we're trying to plan the API here via a README might not be very good imo. It doesn't seem very intuitive to do it this way. For example, the `term` argument you have should be a `string` 😉 

Perhaps making an TS interface of the API (with no actual implementation), documenting the functionality in JSDoc syntax as a PR might make more sense? I'm totally onboard to document before implement but this doesn't seem like the best medium to do it. Perhaps user stories "as a developer using this library..." or something might make more sense? 
@VikeLabs/schedule-courses thoughts?

2020-12-29 23:29 UTC, isaaccormack commented
@amoi Honestly the API isn't that big so whatever means to document it will work. Having it in the readme is nice because its one of the first things the user see. TS interface also works.  

I would user stories are good too but I think we have discussed most of the use cases and they would be largely guesses of the actual users needs. 

Maybe this is work that fits into your existing PR for the API?

2020-12-30 00:02 UTC, aomi commented
@isaaccormack yeah fair point. It's not that complicated.

2020-12-30 20:08 UTC, keithradford commented
@aomi We can def do JSDoc stuff. The way I was looking at it when making this was this way made it so we didn't have to do any code, but if we just add function signatures then add JSDoc  documentation, that makes sense

2021-02-04 05:09 UTC, closed without merging